--Especificação
CREATE OR REPLACE PACKAGE PKG_PACOTE AS 
    PROCEDURE CALCULA_REAJ(P_VAL_ATUAL IN NUMBER);
END PKG_PACOTE;
/


--Corpo (Body)
CREATE OR REPLACE PACKAGE BODY PKG_PACOTE IS 
    PROCEDURE CALCULA_REAJ(P_VAL_ATUAL IN NUMBER) IS 
        V_VAL_REAJ NUMBER (7,2);
    BEGIN 
        V_VAL_REAJ := P_VAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALARIO ATUAL R$ '|| P_VAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALARIO REAJUSTADO R$ '|| V_VAL_REAJ);
    END CALCULA_REAJ;
END PKG_PACOTE;
--//
SET SERVEROUTPUT ON
EXECUTE PKG_PACOTE.CALCULA_REAJ(1500);

GRANT EXECUTE ON PKG_PACOTE TO PUBLIC;

EXECUTE DBMS_OUTPUT.PUT_LINE('TESTE!!!!');

--//

--Especificação
CREATE OR REPLACE PACKAGE PKG_CALCULADORA AS 
    PROCEDURE CALCULA_REAJ(P_VAL_ATUAL IN NUMBER);
    FUNCTION CONVERTE_DOLAR(P_VAL_DOLAR IN NUMBER) RETURN NUMBER;
END PKG_CALCULADORA;
/


--Corpo (Body)
CREATE OR REPLACE PACKAGE BODY PKG_CALCULADORA IS 
    PROCEDURE CALCULA_REAJ(P_VAL_ATUAL IN NUMBER) IS 
        V_VAL_REAJ NUMBER (7,2);
    BEGIN 
        V_VAL_REAJ := P_VAL_ATUAL * 1.25;
        DBMS_OUTPUT.PUT_LINE('SALARIO ATUAL R$ '|| P_VAL_ATUAL);
        DBMS_OUTPUT.PUT_LINE('SALARIO REAJUSTADO R$ '|| V_VAL_REAJ);
    END CALCULA_REAJ;
    
        FUNCTION CONVERTE_DOLAR(P_VAL_DOLAR IN NUMBER) RETURN NUMBER IS
            V_COTACAO NUMBER(3,2) :=5.04;    
            V_REAIS NUMBER(7,2);
        BEGIN
            V_REAIS := P_VAL_DOLAR * V_COTACAO;
            RETURN V_REAIS;
    END CONVERTE_DOLAR;
    
END PKG_CALCULADORA;

--//

SET SERVEROUTPUT ON

EXECUTE PKG_CALCULADORA.CALCULA_REAJ(1320);

EXECUTE DBMS_OUTPUT.PUT_LINE(PKG_CALCULADORA.CONVERTE_DOLAR(45));